server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/convocatoria
    #username: root
    #password:
    username: convocatoriadb
    password: convocatoriadb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

jwt:
  secret: kajshdfklhasdkflhlsifyiqewyfiadhsfjahdsfk # Clave secreta para el token
  expiration: 3600000 # Tiempo de expiración del token -> 1 Hora
  #expiration: 20000 # Tiempo de expiración del token -> 20 segundos